"""오행 (Five elements) relations.

Generating cycle (상생): 木 → 火 → 土 → 金 → 水 → 木
Controlling cycle (상극): 木 × 土 × 水 × 火 × 金 × 木

Relation from a's perspective toward b:
    NEUTRAL        — a == b (비화)
    GENERATING     — a generates b (a → b, a 가 b 를 살림)
    GENERATED_BY   — a is generated by b (b → a, a 가 b 에게서 도움받음)
    CONTROLLING    — a controls b (a × b, a 가 b 를 누름)
    CONTROLLED_BY  — a is controlled by b (b × a, a 가 b 에게 눌림)
"""

from __future__ import annotations

from manseryeok.types import Wuxing, WuxingRelation

# generating[x] = the element that x generates
_GENERATING: dict[Wuxing, Wuxing] = {
    Wuxing.WOOD: Wuxing.FIRE,
    Wuxing.FIRE: Wuxing.EARTH,
    Wuxing.EARTH: Wuxing.METAL,
    Wuxing.METAL: Wuxing.WATER,
    Wuxing.WATER: Wuxing.WOOD,
}

# controlling[x] = the element that x controls
_CONTROLLING: dict[Wuxing, Wuxing] = {
    Wuxing.WOOD: Wuxing.EARTH,
    Wuxing.EARTH: Wuxing.WATER,
    Wuxing.WATER: Wuxing.FIRE,
    Wuxing.FIRE: Wuxing.METAL,
    Wuxing.METAL: Wuxing.WOOD,
}


def wuxing_relation(a: Wuxing, b: Wuxing) -> WuxingRelation:
    """Relation of a → b (from a's perspective).

    Examples:
        wuxing_relation(WOOD, FIRE)  → GENERATING   (a 가 b 를 살림)
        wuxing_relation(WOOD, WATER) → GENERATED_BY (a 가 b 에게서 받음)
        wuxing_relation(WOOD, EARTH) → CONTROLLING  (a 가 b 를 누름)
        wuxing_relation(WOOD, METAL) → CONTROLLED_BY (a 가 b 에게 눌림)
        wuxing_relation(WOOD, WOOD)  → NEUTRAL
    """
    if a == b:
        return WuxingRelation.NEUTRAL
    if _GENERATING[a] == b:
        return WuxingRelation.GENERATING
    if _GENERATING[b] == a:
        return WuxingRelation.GENERATED_BY
    if _CONTROLLING[a] == b:
        return WuxingRelation.CONTROLLING
    if _CONTROLLING[b] == a:
        return WuxingRelation.CONTROLLED_BY
    # Unreachable for valid Wuxing inputs
    raise AssertionError(f"unreachable: {a!r} vs {b!r}")
