"""오행 (Five elements) relations + 지장간 가중 분포.

Generating cycle (상생): 木 → 火 → 土 → 金 → 水 → 木
Controlling cycle (상극): 木 × 土 × 水 × 火 × 金 × 木

Relation from a's perspective toward b:
    NEUTRAL        — a == b (비화)
    GENERATING     — a generates b (a → b, a 가 b 를 살림)
    GENERATED_BY   — a is generated by b (b → a, a 가 b 에게서 도움받음)
    CONTROLLING    — a controls b (a × b, a 가 b 를 누름)
    CONTROLLED_BY  — a is controlled by b (b × a, a 가 b 에게 눌림)
"""

from __future__ import annotations

from manseryeok.data.hidden_stems import HIDDEN_STEMS
from manseryeok.data.stems import stem_by_char
from manseryeok.types import Saju, Wuxing, WuxingRelation

# generating[x] = the element that x generates
_GENERATING: dict[Wuxing, Wuxing] = {
    Wuxing.WOOD: Wuxing.FIRE,
    Wuxing.FIRE: Wuxing.EARTH,
    Wuxing.EARTH: Wuxing.METAL,
    Wuxing.METAL: Wuxing.WATER,
    Wuxing.WATER: Wuxing.WOOD,
}

# controlling[x] = the element that x controls
_CONTROLLING: dict[Wuxing, Wuxing] = {
    Wuxing.WOOD: Wuxing.EARTH,
    Wuxing.EARTH: Wuxing.WATER,
    Wuxing.WATER: Wuxing.FIRE,
    Wuxing.FIRE: Wuxing.METAL,
    Wuxing.METAL: Wuxing.WOOD,
}


def wuxing_relation(a: Wuxing, b: Wuxing) -> WuxingRelation:
    """Relation of a → b (from a's perspective).

    Examples:
        wuxing_relation(WOOD, FIRE)  → GENERATING   (a 가 b 를 살림)
        wuxing_relation(WOOD, WATER) → GENERATED_BY (a 가 b 에게서 받음)
        wuxing_relation(WOOD, EARTH) → CONTROLLING  (a 가 b 를 누름)
        wuxing_relation(WOOD, METAL) → CONTROLLED_BY (a 가 b 에게 눌림)
        wuxing_relation(WOOD, WOOD)  → NEUTRAL
    """
    if a == b:
        return WuxingRelation.NEUTRAL
    if _GENERATING[a] == b:
        return WuxingRelation.GENERATING
    if _GENERATING[b] == a:
        return WuxingRelation.GENERATED_BY
    if _CONTROLLING[a] == b:
        return WuxingRelation.CONTROLLING
    if _CONTROLLING[b] == a:
        return WuxingRelation.CONTROLLED_BY
    # Unreachable for valid Wuxing inputs
    raise AssertionError(f"unreachable: {a!r} vs {b!r}")


def branch_hidden_wuxing(branch_char: str) -> dict[Wuxing, float]:
    """지지 지장간의 오행 비중 (합 1.0).

    단순 가중(본기 0.6 / 중기 0.3 / 여기 0.1, 왕지는 0.7/0.3). 같은 오행 지장간은 합산.
    예: branch_hidden_wuxing("寅") → {목: 0.6, 화: 0.3, 토: 0.1}
    """
    out: dict[Wuxing, float] = {}
    for stem_char, weight in HIDDEN_STEMS[branch_char]:
        wx = stem_by_char(stem_char).wuxing
        out[wx] = out.get(wx, 0.0) + weight
    return out


def wuxing_distribution(saju: Saju, *, hidden: bool = True) -> dict[Wuxing, float]:
    """8글자 오행 분포 (합 8.0).

    천간 4글자는 각 1.0(단일 오행). 지지 4글자는:
    - hidden=True  → 지장간 비중으로 분산 (예 寅 = 목 0.6 / 화 0.3 / 토 0.1)
    - hidden=False → 본기 오행에 1.0 (지장간 무시, 기존 단순 방식)
    """
    dist: dict[Wuxing, float] = dict.fromkeys(Wuxing, 0.0)
    for p in (saju.year, saju.month, saju.day, saju.hour):
        dist[p.stem.wuxing] += 1.0
        if hidden:
            for wx, w in branch_hidden_wuxing(p.branch.char).items():
                dist[wx] += w
        else:
            dist[p.branch.wuxing] += 1.0
    return dist
