"""Type definitions for manseryeok.

All output structures are frozen dataclasses for immutability.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class YinYang(str, Enum):
    YANG = "陽"
    YIN = "陰"


class Wuxing(str, Enum):
    """Five elements (오행)."""

    WOOD = "목"
    FIRE = "화"
    EARTH = "토"
    METAL = "금"
    WATER = "수"


class WuxingRelation(str, Enum):
    """Relation between two wuxing elements."""

    GENERATING = "상생"  # a generates b (a → b)
    CONTROLLING = "상극"  # a controls b (a × b)
    GENERATED_BY = "피생"  # a is generated by b (b → a)
    CONTROLLED_BY = "피극"  # a is controlled by b (b × a)
    NEUTRAL = "비화"  # same element (a == b)


@dataclass(frozen=True, slots=True)
class Stem:
    """천간 (heavenly stem). 10 entries."""

    char: str  # 한자 (甲, 乙, ...)
    kr: str  # 한글 (갑, 을, ...)
    index: int  # 0~9
    wuxing: Wuxing
    yin_yang: YinYang


@dataclass(frozen=True, slots=True)
class Branch:
    """지지 (earthly branch). 12 entries."""

    char: str  # 한자 (子, 丑, ...)
    kr: str  # 한글 (자, 축, ...)
    index: int  # 0~11
    wuxing: Wuxing
    yin_yang: YinYang
    zodiac: str  # 띠 한글 (쥐, 소, ...)


@dataclass(frozen=True, slots=True)
class Pillar:
    """기둥 (年柱·月柱·日柱·時柱) — combination of one Stem and one Branch."""

    stem: Stem
    branch: Branch
    index: int  # 0~59 (60갑자)

    @property
    def char(self) -> str:
        """e.g., '甲子'"""
        return f"{self.stem.char}{self.branch.char}"

    @property
    def kr(self) -> str:
        """e.g., '갑자'"""
        return f"{self.stem.kr}{self.branch.kr}"


@dataclass(frozen=True, slots=True)
class Saju:
    """사주팔자 — 4 pillars (年·月·日·時)."""

    year: Pillar
    month: Pillar
    day: Pillar
    hour: Pillar

    @property
    def day_master(self) -> Stem:
        """일간 (日干) — 'me' in saju interpretation."""
        return self.day.stem

    @property
    def chars(self) -> str:
        """8-char representation, e.g., '壬申辛亥戊申庚申'."""
        return f"{self.year.char}{self.month.char}{self.day.char}{self.hour.char}"


@dataclass(frozen=True, slots=True)
class TodayPillars:
    """오늘의 기둥 — 年柱·月柱·日柱 (시주는 해석에 따라 가변)."""

    year: Pillar
    month: Pillar
    day: Pillar
