"""Type definitions for manseryeok.

All output structures are frozen dataclasses for immutability.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class YinYang(str, Enum):
    YANG = "陽"
    YIN = "陰"


class Wuxing(str, Enum):
    """Five elements (오행)."""

    WOOD = "목"
    FIRE = "화"
    EARTH = "토"
    METAL = "금"
    WATER = "수"


class WuxingRelation(str, Enum):
    """Relation between two wuxing elements."""

    GENERATING = "상생"  # a generates b (a → b)
    CONTROLLING = "상극"  # a controls b (a × b)
    GENERATED_BY = "피생"  # a is generated by b (b → a)
    CONTROLLED_BY = "피극"  # a is controlled by b (b × a)
    NEUTRAL = "비화"  # same element (a == b)


@dataclass(frozen=True, slots=True)
class Stem:
    """천간 (heavenly stem). 10 entries."""

    char: str  # 한자 (甲, 乙, ...)
    kr: str  # 한글 (갑, 을, ...)
    index: int  # 0~9
    wuxing: Wuxing
    yin_yang: YinYang


@dataclass(frozen=True, slots=True)
class Branch:
    """지지 (earthly branch). 12 entries."""

    char: str  # 한자 (子, 丑, ...)
    kr: str  # 한글 (자, 축, ...)
    index: int  # 0~11
    wuxing: Wuxing
    yin_yang: YinYang
    zodiac: str  # 띠 한글 (쥐, 소, ...)


@dataclass(frozen=True, slots=True)
class Pillar:
    """기둥 (年柱·月柱·日柱·時柱) — combination of one Stem and one Branch."""

    stem: Stem
    branch: Branch
    index: int  # 0~59 (60갑자)

    @property
    def char(self) -> str:
        """e.g., '甲子'"""
        return f"{self.stem.char}{self.branch.char}"

    @property
    def kr(self) -> str:
        """e.g., '갑자'"""
        return f"{self.stem.kr}{self.branch.kr}"


@dataclass(frozen=True, slots=True)
class Saju:
    """사주팔자 — 4 pillars (年·月·日·時)."""

    year: Pillar
    month: Pillar
    day: Pillar
    hour: Pillar

    @property
    def day_master(self) -> Stem:
        """일간 (日干) — 'me' in saju interpretation."""
        return self.day.stem

    @property
    def chars(self) -> str:
        """8-char representation, e.g., '壬申辛亥戊申庚申'."""
        return f"{self.year.char}{self.month.char}{self.day.char}{self.hour.char}"


@dataclass(frozen=True, slots=True)
class TodayPillars:
    """오늘의 기둥 — 年柱·月柱·日柱 (시주는 해석에 따라 가변)."""

    year: Pillar
    month: Pillar
    day: Pillar


@dataclass(frozen=True, slots=True)
class DaeunPeriod:
    """한 대운 — 시작 나이부터 10년간."""

    start_age: int  # 이 대운이 시작하는 만 나이
    pillar: Pillar  # 대운 간지


@dataclass(frozen=True, slots=True)
class Daeun:
    """대운(大運) — 평생 고정 시퀀스. 사주 계산 시 1회 산출·저장·반복 사용.

    '지금 몇 대운인가'만 현재 나이로 인덱싱한다(at_age).
    """

    start_age: int  # 대운수 (첫 대운 시작 만 나이)
    forward: bool  # 순행(True) / 역행(False)
    periods: tuple[DaeunPeriod, ...]

    def at_age(self, age: int) -> DaeunPeriod | None:
        """주어진 만 나이에 해당하는 대운. 첫 대운 시작 전이면 None."""
        chosen: DaeunPeriod | None = None
        for p in self.periods:
            if p.start_age <= age:
                chosen = p
            else:
                break
        return chosen
